### ISSUE TITLE
jupyter notebook example steps fail module import

### ISSUE THREAD

**Issue by alexjmacdonald** [grapl-security/grapl#398]
### What version of Grapl are you using?

staging @ f5f808b80456128a26c84cd2e932cac1dcf0acd7

### Is this behavior happening in AWS, locally, or both?

Locally.

#### OS and OS version

OSX 10.15.7

### Steps to reproduce the issue

- Visit localhost:1234 to open jupyter notebook on grapl-notebook, log in with example password
- Run first step:

```
from grapl_analyzerlib.prelude import *
from grapl_analyzerlib.nodes.lens_node import *
```

### Expected behavior

No output.

### Observed behavior

Module fails import:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-269ae69c16ab> in <module>
      1 from grapl_analyzerlib.prelude import *
----> 2 from grapl_analyzerlib.nodes.lens_node import *
ModuleNotFoundError: No module named 'grapl_analyzerlib.nodes.lens_node'
```

**Comment by alexjmacdonald** [comment]
changing `lens_node` to `lens` gets me past, then `EngagementView` is undefined in subsequent steps

**Comment by alexjmacdonald** [comment]
trying `from grapl_analyzerlib.nodes.engagement import EngagementView`:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-32532135cd2f> in <module>
      1 from grapl_analyzerlib.prelude import *
      2 from grapl_analyzerlib.nodes.lens import *
----> 3 from grapl_analyzerlib.nodes.engagement import EngagementView

~/.local/lib/python3.8/site-packages/grapl_analyzerlib/nodes/engagement.py in <module>
     14 
     15 
---> 16 GRAPL_LOG_LEVEL = os.getenv("GRAPL_LOG_LEVEL")
     17 LEVEL = "ERROR" if GRAPL_LOG_LEVEL is None else GRAPL_LOG_LEVEL
     18 LOGGER = logging.getLogger(__name__)

NameError: name 'os' is not defined
```

meanwhile, this file does an `import os` on line 3?  I know some Python but I'm out of my depth here.

**Comment by colin-grapl** [comment]
Yeah so this notebook is out of date for sure. That os.getenv is really strange, but it's also almost certainly a bug that doesn't exist today.

Part of the problem is that the notebook Dockerfile installs the version of grapl_analyzerlib on PyPI, but it should pull in the dependency the same way the other images do.

**Comment by wimax-grapl** [comment]
I'll take this + add some QA to it
