### ISSUE TITLE
Run grapl_analyzerlib Github Actions inside monorepo

### ISSUE THREAD

**Issue by wittekm** [grapl-security/grapl#90]
As part of #87 the grapl_analyzerlib was pulled into this repo;
but the associated `workflows.yml` is not in the correct dir:
https://github.com/grapl-security/grapl/pull/87/files#diff-ec8df80671b7876b8f2904b09f6bf91d

**Comment by wittekm** [comment]
(also, it may need some rejiggeringof directories to get it working right)

**Comment by jgrillo-grapl** [comment]
This is addressed here https://github.com/grapl-security/grapl/pull/87

**Comment by wittekm** [comment]
Thanks Jesse!

Instead of explicitly defining that we `pip install black mypy` here, could we use the mechanism in here:
https://github.com/wittekm/grapl_analyzerlib/commit/0eef2150c0adf80e50217e99c529f889318c7ff0#diff-5ab0aecf70891baa7cf39db5f248f58cR36

What this does is, it looks at the `setup.py`
```
https://github.com/grapl-security/grapl/blob/staging/src/python/grapl_analyzerlib/setup.py#L38
```
and installs:
- `.` (the "install_requires" stuff)
- `extras_require["dev"]` (the black/mypy stuff)

the reason being that this keeps our CI build system/reqs, and the requirements you use when you install it locally for development, exactly the same

**Comment by jgrillo-grapl** [comment]
Hi @wittekm,

Thanks for the feedback! Let me first describe where we currently are at, then address your concern. Moving grapl_analyzerlib into the grapl monorepo has introduced some additional complexity as compared to a workflow where it's the only project present. There are four moving parts at play here:

1. The build system. Currently grapl builds are run locally by executing `docker-compose -f docker-compose.yml -f docker-compose.build.yml build` in the project root (see https://github.com/grapl-security/grapl/blob/staging/CONTRIBUTING.md#changes-to-code-or-documentation). This builds all the code, (will run tests once we turn them on e.g. here https://github.com/grapl-security/grapl/blob/staging/src/python/analyzer_executor/Dockerfile#L6), and builds deployment containers for running your changes locally with `docker-compose -f docker-compose.yml -f docker-compose.build.yml up`.

2. PR lints. This is conducted in the [grapl-lint workflow](https://github.com/grapl-security/grapl/blob/staging/.github/workflows/grapl-lint.yml). The purpose of this workflow is to check that the entire grapl repository is formatted properly--i.e run `black --check` on everything and `rustfmt --check` on everything in `src/rust`.

3. PR builds. This is conducted in the [grapl-build workflow](https://github.com/grapl-security/grapl/blob/staging/.github/workflows/grapl-build.yml). Note this executes exactly the same commands you'd use locally for dev builds (see 1 above).

4. Release builds. These are conducted in the [grapl-release workflow](https://github.com/grapl-security/grapl/blob/staging/.github/workflows/grapl-release.yml). They use the same `docker-compose build` invocation with some additional arguments to compile release artifacts. There is also a bunch of automation to push images to Dockerhub, pull out CDK release artifacts and attach them to the Github release, and push python libs to PyPI (see also https://github.com/grapl-security/grapl/pull/101).

I've tried to adhere as closely as possible to the precept that we should have the same dev workflow as is used in production. I think this has by-and-large been successful. With the python projects you can `pip install .` or `python setup.py test` in your local virtualenv for rapid feedback, or you can `docker-compose -f docker-compose.yml -f docker-compose.build.yml build` to build everything for local manual (and eventually, automated) integration testing. Those same processes are employed in the build system, and during releases.

There is plenty of room for improvement here. In addition to `docker-compose build` we should be using [dobi](https://github.com/dnephin/dobi) for executing our container builds (see https://github.com/grapl-security/grapl/issues/86). This should allow us to parallelize the build process and significantly reduce build times. Tests need to be run at build time, integration tests need to be written, etc.

So, to address your specific concern, I think coupling a dev dependency of one specific python library to the global project linting workflow wouldn't be quite right, however it might make sense to introduce some more structure to make it easier to develop grapl locally? My python packaging knowledge is somewhat dated, I'd definitely be interested to hear if you have any suggestions.

**Comment by wittekm** [comment]
Greatly appreciate the explanation :) will give it a read-thru this weekend!
